import type { SystemEntityConfig } from "./system-types";

/** 租户管理的真实接口与字段契约。 */
export const tenantEntityConfig: SystemEntityConfig = {
  permissionPrefix: "system:tenant",
  basePath: "/system/tenant",
  title: "租户管理",
  eyebrow: "Tenant Directory",
  description: "维护平台租户空间、联系人、账号容量和服务有效期。",
  entityName: "租户",
  primaryLabelKey: "tenantName",
  searchFields: [
    { key: "tenantName", label: "租户名称", placeholder: "输入租户名称" },
    { key: "tenantCode", label: "租户编码", placeholder: "输入租户编码" },
    { key: "contactName", label: "联系人", placeholder: "输入联系人" },
  ],
  tableColumns: [
    { key: "tenantName", label: "租户名称", minWidth: 180 },
    { key: "tenantCode", label: "租户编码", minWidth: 150, kind: "code" },
    { key: "contactName", label: "联系人", minWidth: 120 },
    { key: "contactPhone", label: "联系电话", minWidth: 140 },
    { key: "userLimit", label: "账户上限", width: 100 },
    { key: "expireTime", label: "到期时间", width: 180, kind: "datetime" },
  ],
  formFields: [
    {
      key: "tenantName",
      label: "租户名称",
      type: "text",
      required: true,
      placeholder: "例如：专项服务中心",
    },
    { key: "tenantCode", label: "租户编码", type: "text", placeholder: "例如：SERVICE_CENTER" },
    { key: "contactName", label: "联系人", type: "text" },
    { key: "contactPhone", label: "联系电话", type: "text" },
    { key: "contactEmail", label: "联系邮箱", type: "text" },
    { key: "userLimit", label: "账户上限", type: "number", min: 1, max: 100000 },
    { key: "expireTime", label: "到期时间", type: "datetime" },
    { key: "domain", label: "租户域名", type: "text" },
    { key: "logo", label: "Logo 地址", type: "text" },
    { key: "sortOrder", label: "排序", type: "number", min: 0, max: 9999 },
    { key: "address", label: "租户地址", type: "textarea", span: 2 },
    { key: "description", label: "租户说明", type: "textarea", span: 2 },
    { key: "remark", label: "备注", type: "textarea", span: 2 },
  ],
  initialValues: {
    tenantName: "",
    tenantCode: "",
    contactName: "",
    contactPhone: "",
    contactEmail: "",
    userLimit: 100,
    expireTime: "",
    domain: "",
    logo: "",
    sortOrder: 0,
    address: "",
    description: "",
    remark: "",
  },
};

/** 部门管理的真实接口与字段契约。 */
export const departmentEntityConfig: SystemEntityConfig = {
  permissionPrefix: "system:dept",
  basePath: "/system/dept",
  title: "部门管理",
  eyebrow: "Organization Directory",
  description: "维护组织层级、部门编码、负责人和所属区域。",
  entityName: "部门",
  primaryLabelKey: "deptName",
  searchFields: [
    { key: "deptName", label: "部门名称", placeholder: "输入部门名称" },
    { key: "deptCode", label: "部门编码", placeholder: "输入部门编码" },
    { key: "location", label: "位置", placeholder: "输入办公位置" },
  ],
  tableColumns: [
    { key: "deptName", label: "部门名称", minWidth: 180 },
    { key: "deptCode", label: "部门编码", minWidth: 150, kind: "code" },
    { key: "leaderName", label: "负责人", minWidth: 120 },
    { key: "phone", label: "联系电话", minWidth: 140 },
    { key: "location", label: "办公位置", minWidth: 160 },
    { key: "regionCode", label: "区域编码", width: 120 },
  ],
  formFields: [
    { key: "deptName", label: "部门名称", type: "text", required: true },
    { key: "deptCode", label: "部门编码", type: "text" },
    { key: "parentId", label: "上级部门", type: "tree", optionsPath: "/system/dept/options" },
    { key: "leaderName", label: "负责人", type: "text" },
    { key: "phone", label: "联系电话", type: "text" },
    { key: "email", label: "邮箱", type: "text" },
    { key: "location", label: "办公位置", type: "text" },
    { key: "regionCode", label: "区域编码", type: "text" },
    { key: "sortOrder", label: "排序", type: "number", min: 0, max: 9999 },
    { key: "remark", label: "备注", type: "textarea", span: 2 },
  ],
  initialValues: {
    deptName: "",
    deptCode: "",
    parentId: "",
    leaderName: "",
    phone: "",
    email: "",
    location: "",
    regionCode: "",
    sortOrder: 0,
    remark: "",
  },
};

/** 岗位管理的真实接口与字段契约。 */
export const postEntityConfig: SystemEntityConfig = {
  permissionPrefix: "system:post",
  basePath: "/system/post",
  title: "岗位管理",
  eyebrow: "Position Directory",
  description: "维护岗位名称、唯一编码、上下级关系和启用状态。",
  entityName: "岗位",
  primaryLabelKey: "postName",
  searchFields: [
    { key: "postName", label: "岗位名称", placeholder: "输入岗位名称" },
    { key: "postCode", label: "岗位编码", placeholder: "输入岗位编码" },
  ],
  tableColumns: [
    { key: "postName", label: "岗位名称", minWidth: 180 },
    { key: "postCode", label: "岗位编码", minWidth: 160, kind: "code" },
    { key: "parentId", label: "上级岗位 ID", minWidth: 190 },
    { key: "sortOrder", label: "排序", width: 90 },
    { key: "remark", label: "备注", minWidth: 200 },
  ],
  formFields: [
    { key: "postName", label: "岗位名称", type: "text", required: true },
    { key: "postCode", label: "岗位编码", type: "text" },
    { key: "parentId", label: "上级岗位", type: "tree", optionsPath: "/system/post/options" },
    { key: "sortOrder", label: "排序", type: "number", min: 0, max: 9999 },
    { key: "remark", label: "备注", type: "textarea", span: 2 },
  ],
  initialValues: {
    postName: "",
    postCode: "",
    parentId: "",
    sortOrder: 0,
    remark: "",
  },
};
